compiler: g++

# This is only for Porthos right now
# install Porthos dependencies
install:
  - "sudo apt-get -y install libssl-dev g++ make"
  - "cd Porthos/
    && ./setup-eigen.sh
    && make clean && make -j"

