language: python
python:
  - "3.6"

compiler: g++

before_install:
  # Codecov
  - sudo pip install codecov

# This is only for Porthos right now
# install Porthos dependencies
install:
  - "sudo apt-get -y install libssl-dev g++ make"
  - "cd Porthos/
    && ./setup-eigen.sh"
    
script:
  - "make clean && make -j"
  - "chmod +x get_code_cov"
  - ./get_code_cov
  - codecov
  
  after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)

