language: python
python:
  - "3.6"

compiler: g++

# This is only for Porthos right now
# install Porthos dependencies
install:
  - "sudo apt-get -y install libssl-dev g++ make"
  - "cd Porthos/
    && ./setup-eigen.sh"
    
script:
  - "make clean && make -j"

